GET http://localhost:3000/api/posts

###
POST http://localhost:3000/api/posts

###
GET http://localhost:3000/api/posts/22

###
GET http://localhost:3000/api/posts/author/22



###
GET http://localhost:3000/api/authors

###
POST http://localhost:3000/api/authors